repos:
  - repo: https://github.com/ambv/black
    rev: 23.10.0
    hooks:
      - id: black
        exclude: processor/database/alembic/versions/
        types: [python]
        language: system
        files: ^(processor/|scripts/)

  - repo: https://github.com/commitizen-tools/commitizen
    rev: 3.10.0
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages:
          - push

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.0
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
        types: [python]
        language: system
        files: ^(processor/|scripts/)
       
